### ISSUE TITLE
Chapter 1 to 7

### ISSUE THREAD

**Issue by aliir74** [AUT-CEIT/AP101#1]
Where is chapter 1 to 7?

**Comment by 1995parham** [comment]
I think these chapters are based on BlueJ book so we do not have any slides for them. but lets ask @smahmadpanah

**Comment by smahmadpanah** [comment]
You can find the slides on Fileserver, Dr. Noorhosseini's folder.
Or remind me to bring them anytime you want.

*Seyed Mohammad Mehdi Ahmadpanah*
Graduate Research Assistant at Formal Security Lab
Department of Computer Engineering and IT
Amirkabir University of Technology
http://ceit.aut.ac.ir/~ahmadpanah
